In [36]:
keywords = {
    "Anggaran": [
        "dana",
        "anggaran",
        "apbn",
        "biaya",
    ],

    "Politik":[
        "prabowo",
        "kampanye",
        "politik",

    ],

    "Kualitan Pangan":[
        'bergizi',
        'belatung',
        'keracunan',
        'makanan',
    ],
    "Distribusi":[
        'distribusi'
        'penyaluran'
        'pengiriman'
        'daerah'
        'sampai'
    ],

    "Ekonomi":[
        'ekonomi',
        'umkm',
        'lapangan',
        'lokal',
        'kerja',
        'masyarakat',
        'banyak',
    ],

    "Tata Kelola":[
        'aturan'
        'regulasi'
        'pengawasan'
        'evaluasi'
        'pelaksanaan'
        'mekanisme'
        'koordinasi'
        'kementerian'
        'bgn'
        'prosedur'
    ],

    "Sasaran Penerima":[
        'siswa'
        'anak sekolah'
        'pelajar'
        'penerima'
        'target'
        'anak sd'
        'murid'
    ],

    "lainnya":[
        'makanan'
    ]
}

In [37]:
#import libary yang dibutuhkan
from collections import Counter
import re
import pandas as pd
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, ArrayDictionary, StopWordRemover
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [38]:
# buat nyari kata yang sering muncul sesuai label yg diminta



text = " ".join(
    train[train['label'] == 'lainnya']['full_text']
)
words = text.lower().split()
counter = Counter(words)
print(counter.most_common(90))

NameError: name 'train' is not defined

In [ ]:
#buat baca datanya


train = pd.read_excel("excel/case_1_labeled_data.xlsx")
test = pd.read_excel("excel/case_1_text_to_predict.xlsx")
# train['clean_text'] = train['text'].apply(clean_text)
# test['clean_text'] = test['text'].apply(clean_text)

train.head()

In [ ]:
# 1. PROSES CASE FOLDING

test = pd.read_excel("excel/case_1_text_to_predict.xlsx")

def clean_text(text):
    if isinstance(text, str):
        return text.lower()
    return text

test['clean_text'] = test['full_text'].apply(clean_text) 

print("Setelah Case Folding:")

display(test[['full_text', 'clean_text']].head())

Setelah Case Folding:

,full_text,clean_text
0,@yeahhhmaybe mbg di sekolah kota saya belum ad...,@yeahhhmaybe mbg di sekolah kota saya belum ad...
1,@thefineshytguy WKWKKdidaerah ku pun yg dapat ...,@thefineshytguy wkwkkdidaerah ku pun yg dapat ...
2,"@ARSIPAJA Tai tau enggak ,gak semua sekolah da...","@arsipaja tai tau enggak ,gak semua sekolah da..."
3,"Gencar Cegah Stunting, MBG Telah Capai 49% Sas...","gencar cegah stunting, mbg telah capai 49% sas..."
4,140 siswa kupang Keracunan program MBG @prabowo,140 siswa kupang keracunan program mbg @prabowo

In [ ]:
def remove_special_characters(text: str) -> str:
    #remove karakter spesial
    processed_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return processed_text

test['clean_text'] = test['clean_text'].apply(remove_special_characters)

print("Setelah Remove Special Characters:")
display(test[['full_text', 'clean_text']].head())

Setelah Remove Special Characters:

,full_text,clean_text
0,@yeahhhmaybe mbg di sekolah kota saya belum ad...,yeahhhmaybe mbg di sekolah kota saya belum ada...
1,@thefineshytguy WKWKKdidaerah ku pun yg dapat ...,thefineshytguy wkwkkdidaerah ku pun yg dapat m...
2,"@ARSIPAJA Tai tau enggak ,gak semua sekolah da...",arsipaja tai tau enggak gak semua sekolah dapa...
3,"Gencar Cegah Stunting, MBG Telah Capai 49% Sas...",gencar cegah stunting mbg telah capai 49 sasar...
4,140 siswa kupang Keracunan program MBG @prabowo,140 siswa kupang keracunan program mbg prabowo

In [ ]:
def removedigitangka(text: str) -> str:
    # menghilangkan digit angka
    text = re.sub(r'\d+', '', text)
    return text

test['clean_text'] = test['clean_text'].apply(removedigitangka)

print("Setelah Remove digit:")
display(test[['full_text', 'clean_text']].head())

Setelah Remove digit:

,full_text,clean_text
0,@yeahhhmaybe mbg di sekolah kota saya belum ad...,yeahhhmaybe mbg di sekolah kota saya belum ada...
1,@thefineshytguy WKWKKdidaerah ku pun yg dapat ...,thefineshytguy wkwkkdidaerah ku pun yg dapat m...
2,"@ARSIPAJA Tai tau enggak ,gak semua sekolah da...",arsipaja tai tau enggak gak semua sekolah dapa...
3,"Gencar Cegah Stunting, MBG Telah Capai 49% Sas...",gencar cegah stunting mbg telah capai sasaran...
4,140 siswa kupang Keracunan program MBG @prabowo,siswa kupang keracunan program mbg prabowo

In [ ]:
def removeurl(text: str) -> str:
    # menghilangkan url
    text = re.sub(r'https?:\/\/\S+','',text)
    return text

test['clean_text'] = test['clean_text'].apply(removeurl)

print("Setelah Remove url:")
display(test[['full_text', 'clean_text']].head())

Setelah Remove url:

,full_text,clean_text
0,@yeahhhmaybe mbg di sekolah kota saya belum ad...,yeahhhmaybe mbg di sekolah kota saya belum ada...
1,@thefineshytguy WKWKKdidaerah ku pun yg dapat ...,thefineshytguy wkwkkdidaerah ku pun yg dapat m...
2,"@ARSIPAJA Tai tau enggak ,gak semua sekolah da...",arsipaja tai tau enggak gak semua sekolah dapa...
3,"Gencar Cegah Stunting, MBG Telah Capai 49% Sas...",gencar cegah stunting mbg telah capai sasaran...
4,140 siswa kupang Keracunan program MBG @prabowo,siswa kupang keracunan program mbg prabowo

In [ ]:
def stop_stem(text):
    # Stopword removal
    with open('Kamus/kamus.txt') as kamus:
        word = kamus.readlines()
        list_stopword = [line.replace('\n', '') for line in word]
    dictionary = ArrayDictionary(list_stopword)
    stopword = StopWordRemover(dictionary)
    text = stopword.remove(text)

    # Stemming
    factory_stemmer = StemmerFactory()
    stemmer = factory_stemmer.create_stemmer()
    text = stemmer.stem(text)

    return text

test['clean_text'] = test['clean_text'].apply(stop_stem)

print("Setelah Stopword Removal + Stemming:")
display(test[['full_text', 'clean_text']].head())

NameError: name 'ArrayDictionary' is not defined

In [ ]:
import sys

!{sys.executable} -m pip install PySastrawi
!{sys.executable} -m pip install openpyxl

Requirement already satisfied: PySastrawi in c:\users\zyog1\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.2.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\zyog1\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\zyog1\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, ArrayDictionary, StopWordRemover
print("Import berhasil!")

Import berhasil!